name: "Analise de código"

on:
  pull_request:
    
    branches: [ master ]
  schedule:
    - cron: '38 19 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: [self-hosted, ubuntu-20.04]
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Inicializando scaneamento de código
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Analysis de CodeQL
      uses: github/codeql-action/analyze@v1
