name: CODE REVIEW
on:
  workflow_dispatch:
  pull_request:    
    branches: [ master ]
  #schedule:
   # - cron: '38 19 * * 1'
jobs:
  analyze:
    name: Code Review
    runs-on: [ubuntu-20.04, self-hosted]    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Code Scan
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: CodeQL Analysis
      uses: github/codeql-action/analyze@v1
