name: Nightly
on:
  schedule:
    - cron: '0 0 * * *' # run at 0 AM UTC

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Deploy Ubuntu vim, NGINX
        if: matrix.os == 'ubuntu-20.04'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/renatonadolny/less/releases/56837515/assets{?name,label}
          release_id: 56837515
          asset_path: ./less-${{ github.event.release.tag_name }}-commit.tgz # path to archive to upload
          asset_name: less_ubuntu-nightly-$$.tgz # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/tgz # required by GitHub API
          max_releases: 30 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
