name: Nightly
on:
  workflow_dispatch:
    
  release:
    types: [published]
  
jobs:
  update:
    runs-on: ubuntu-20.04
    
    name: Nightly		
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
 
    steps:
    
          
    - name: Deploy Ubuntu vim, NGINX
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/checkout@v2.4.0
    - name: Install
      run: |
          sudo apt-get install gcc
          sudo apt-get install vim
          sudo apt-get install nginx
          
    - uses: Actions-R-Us/actions-tagger@master
      with:
        publish_latest: true
        publish_latest_tag: true
      env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
