name: Release Management
on: 
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
  schedule:
   - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@master
        with:
           node-version: "13.x" 
      - name: Ubuntu dependencies
        run: sudo apt-get install libgtk-3-dev build-essential
      - name: Download Project from github
        run: sudo apt-get install libgtk-3-dev build-essential wget
     
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          run: |
            sh configure
            
            
            
      
