name: Nightly

on:
workflow_dispatch:

jobs:
  release-project:
    name: Release Ubuntu LESS
		runs-on: ubuntu-latest
			
		steps:
			- name: Download Conteudo site
        uses: actions/download-artifact@v2
        with:
        	name: static-less
      - name: Conteudo dos arquivos
			  uses: thedoctor0/zip-release@master
			  with:
			    filename: less-project.tar
			- name: Criar Release GitHub
			  id: create-new-release
			  uses: actions/create-release@v1
			  env:
				  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
			  with:
			    tag_name: v${{ github.run_number}}
				  release_name: Release V${{ github.run_number}}
			- name: Upload asset to github release-project
			  uses: actions/upload-release-asset@v1
			  env:
				  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
			  with:
			    upload_url: ${{ steps.create-new-release.outputs.upload_url}}
				  asset_path: ./less.tar
				  asset_name: site-v${{ github.run_number}}.tar
				  asset_content_type: application/tar

