name: Release Management
on: 
  release:
    types: [created]
  workflow_dispatch:
  schedule:
   - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@master
        with:
           node-version: "13.x" 
      - name: Ubuntu dependencies
        run: sudo apt-get install libgtk-3-dev build-essential
     
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Build Qode binary
        run: node build.js
        env:
          SYNC_GIT_SUBMODULE: 1
      
      - name: Compress files
        uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: ./node/out/Release
          files: |
            ./qode
          outPath: qode-linux-x64-${{github.event.release.tag_name}}.tar.gz
      
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: qode-*.tar.gz
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
