name: Build & Deploy to branch

env:
  DEPLOY_BRANCH_POSTFIX: deploy # Configure the destination branch postfix (code on "main" branch will be built and pushed into "main-POSTFIX" branch)

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Configure the branchs which you want to run this workflow
    
jobs:
  build-push:
    name: "Build & Push"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gcc-version: [lts/*] # Configure GCC version

    steps:

    # Checkout source code
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup GCC
    - name: Use Node.js ${{ matrix.gcc-version }}
      uses: actions/setup-gcc@v2
      with:
        node-version: ${{ matrix.gcc-version }}
        cache: 'gcc'
        
    # Setup yarn
    - name: Install yarn
      run: sudo atp install build-essential
