name: Release Management
on: 
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
  schedule:
   - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          uses: |
            sudo apt-get install libgtk-3-dev build-essential wget
            sh configure
            
            
            
      
