name: rodar aplicação
on: 
  workflow_dispatch:
  schedule:
   - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: |
            sudo apt-get update
            sudo apt-get install gcc cmake
            sudo gcc github.repository==main.c
